**EJERCICIO 1** Crea un array unidimensional de 10 elementos y extrae: 

- El primer elemento.


- Lo elementos que están en posición impar.


- Los cuatro primeros elementos.


- Los últimos tres elementos.


- Los elemtos entre el 4 y el 8. 

In [2]:
unidimensional = np.arange(10)
unidimensional

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# El primer elemento

unidimensional[0]

0

In [7]:
# Lo elementos que están en posición impar.

unidimensional[::2]

array([0, 2, 4, 6, 8])

In [8]:
# Los cuatro primeros elementos.

unidimensional[:4]

array([0, 1, 2, 3])

In [10]:
# Los últimos tres elementos

unidimensional[-3:]

array([7, 8, 9])

In [11]:
# Los elemtos entre el 4 y el 8.

unidimensional[4:9]

array([4, 5, 6, 7, 8])

**EJERCICIO 2** Crea un array de dos dimensiones y extrae:

- La primera fila y todas las columnas


- Todas las filas pares


- La primera columna y todas las filas

In [13]:
bidimensional = np.random.rand(10, 5)
bidimensional

array([[0.89698917, 0.83631042, 0.89116935, 0.49535321, 0.85058161],
       [0.99499667, 0.12949272, 0.11130355, 0.4826603 , 0.33689467],
       [0.89754873, 0.51246462, 0.83618508, 0.61225527, 0.51596033],
       [0.09524737, 0.36050704, 0.16023951, 0.17920753, 0.50486206],
       [0.4180467 , 0.45722924, 0.01457002, 0.53685364, 0.19378491],
       [0.83359772, 0.57588939, 0.31301067, 0.80843636, 0.96668165],
       [0.67046014, 0.22787148, 0.86417004, 0.32664176, 0.59965362],
       [0.68278509, 0.80481625, 0.55302407, 0.77164912, 0.79177735],
       [0.57128618, 0.11307867, 0.39232651, 0.4594877 , 0.54343471],
       [0.03347032, 0.7911611 , 0.77563676, 0.23023213, 0.52642975]])

In [16]:
# La primera fila y todas las columnas

bidimensional[1,]

array([0.99499667, 0.12949272, 0.11130355, 0.4826603 , 0.33689467])

In [19]:
# Todas las filas pares

bidimensional[::2,]

array([[0.89698917, 0.83631042, 0.89116935, 0.49535321, 0.85058161],
       [0.89754873, 0.51246462, 0.83618508, 0.61225527, 0.51596033],
       [0.4180467 , 0.45722924, 0.01457002, 0.53685364, 0.19378491],
       [0.67046014, 0.22787148, 0.86417004, 0.32664176, 0.59965362],
       [0.57128618, 0.11307867, 0.39232651, 0.4594877 , 0.54343471]])

In [24]:
# La primera columna y todas las filas

bidimensional[:,0]

array([0.89698917, 0.99499667, 0.89754873, 0.09524737, 0.4180467 ,
       0.83359772, 0.67046014, 0.68278509, 0.57128618, 0.03347032])

**EJERICIO 3**

- Crea una matriz mutidimensional de 2 x 3 x 5 de unos y haz una copia de la matriz multidimensional. 


- Reemplaza los siguientes valores:

    - Array 0, fila 2, columna 3 por 100
    
    - Array 1, fila 1, columna 4 por 100
    
    - Array 0, fila 0, columna 2 por 100
    
    - Array 1, fila 2, columna 1 por 100


- Haz una copia de la matriz anterior. Crea una matriz de unos de 5 x 2 x 3 e intenta sumarla a la copia. ¿Se puede?  ¿Por qué?


- Trata de modificar las dimensiones de tu matriz de unos para poder sumarla con la copia. Hazlo de las dos formas_

    - `transpose`
    
    - `reshape`
    
    
    
- Vuelve a intentar sumar las dos matrices

In [26]:
# Crea una matriz mutidimensional de 2 x 3 x 5 de unos y haz una copia
## de la matriz multidimensional.

multidimensional = np.ones((2,3,5))
multidimensional

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [27]:
# Array 0, fila 2, columna 3 por 100
multidimensional[0, 2, 3] = 100

In [29]:
# Array 1, fila 1, columna 4 por 100
multidimensional[1, 1, 4] = 100

In [30]:
# Array 0, fila 0, columna 2 por 100
multidimensional[0, 0, 2] = 100

In [31]:
# Array 1, fila 2, columna 1 por 100
multidimensional[1, 2, 1] = 100

In [32]:
multidimensional

array([[[  1.,   1., 100.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1., 100.,   1.]],

       [[  1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1., 100.],
        [  1., 100.,   1.,   1.,   1.]]])

In [33]:
# Haz una copia de la matriz anterior. Crea una matriz de unos de 5 x 2 x 3 e intenta sumarla a la copia. 
# ¿Se puede? ¿Por qué?

multidimensional_copia = multidimensional.copy()
multidimensional_copia

array([[[  1.,   1., 100.,   1.,   1.],
        [  1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1., 100.,   1.]],

       [[  1.,   1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1., 100.],
        [  1., 100.,   1.,   1.,   1.]]])

In [35]:
# crear una nueva matriz de unos
unos = np.ones((5,2,3))
unos

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
# suma

np.add(multidimensional_copia, unos)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

No se puede realizar la suma porque los *arrays* tienen distintas formas. 

In [37]:
# cambiar la forma del array "unos" usando transpose

unos_transpose = np.transpose(unos, (1,2,0))
unos_transpose

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [40]:
# cambiar la forma del array "unos" usando reshape

unos_reshape = np.reshape(unos, (2,3,5))
unos_reshape

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [41]:
# volvemos a sumar con la transpuesta

np.add(multidimensional_copia, unos_transpose)

array([[[  2.,   2., 101.,   2.,   2.],
        [  2.,   2.,   2.,   2.,   2.],
        [  2.,   2.,   2., 101.,   2.]],

       [[  2.,   2.,   2.,   2.,   2.],
        [  2.,   2.,   2.,   2., 101.],
        [  2., 101.,   2.,   2.,   2.]]])

In [42]:
# volvemos a sumar con el reshape

np.add(multidimensional_copia, unos_reshape)

array([[[  2.,   2., 101.,   2.,   2.],
        [  2.,   2.,   2.,   2.,   2.],
        [  2.,   2.,   2., 101.,   2.]],

       [[  2.,   2.,   2.,   2.,   2.],
        [  2.,   2.,   2.,   2., 101.],
        [  2., 101.,   2.,   2.,   2.]]])