In [1]:
import numpy as np

**EJERCICIO 1** En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 



- Crea un *array*, puede ser bidimensional o multidimensional! Eso si, los valores tienen que estar entre 0-100

- Calcula: 


    - La media de los elementos
    
    
    - La media de las columnas y redondéalo a dos decimales
    
    
    - El valor máximo de cada fila
    
    
    - El valor mínimo de cada fila
    
    
    - Hay algun valor que sea mayor que 90 en tu *array* 
    
    
    - Donde los podemos encontrar, cuáles son sus índices
   
    
    - Ordena el *array* de mayor a menor

📝 **NOTA** En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos. 

1️⃣ En caso de que sea tridimensional

In [7]:
# Crea un array

tridimensional = np.random.randint(1, 100, (2, 6,5))
tridimensional

array([[[90, 32, 90, 53, 92],
        [83, 35, 23, 26, 62],
        [78, 86, 53,  1, 48],
        [75, 55, 26,  1, 75],
        [64, 68, 42, 18,  2],
        [83, 51, 49, 27, 65]],

       [[ 3, 69, 82, 39, 44],
        [37, 22, 82, 98, 56],
        [81, 70, 60, 46, 49],
        [18, 95,  3, 49, 45],
        [95,  2, 39, 64, 69],
        [18,  6, 35, 66, 48]]])

In [8]:
# La media de los elementos

np.mean(tridimensional) 

50.71666666666667

In [12]:
# La media de las columnas y redondéalo a dos decimales

np.round(np.mean(tridimensional, axis = 1) , 2)

array([[78.83, 54.5 , 47.17, 21.  , 57.33],
       [42.  , 44.  , 50.17, 60.33, 51.83]])

In [13]:
# El valor máximo de cada fila

np.max(tridimensional, axis = 2)


array([[92, 83, 86, 75, 68, 83],
       [82, 98, 81, 95, 95, 66]])

In [14]:
# El valor mínimo de cada fila

np.min(tridimensional, axis = 2)


array([[32, 23,  1,  1,  2, 27],
       [ 3, 22, 46,  3,  2,  6]])

In [15]:
# Hay algun valor que sea mayor que 90 en tu *array* 
np.any(tridimensional)

True

In [16]:
# Donde los podemos encontrar, cuáles son sus índices

np.where(tridimensional > 90)

(array([0, 1, 1, 1]), array([0, 1, 3, 4]), array([4, 3, 1, 0]))

In [29]:
# Ordena el *array* de mayor a menor

-np.sort(-tridimensional, axis = 1)

array([[[90, 86, 90, 53, 92],
        [83, 68, 53, 27, 75],
        [83, 55, 49, 26, 65],
        [78, 51, 42, 18, 62],
        [75, 35, 26,  1, 48],
        [64, 32, 23,  1,  2]],

       [[95, 95, 82, 98, 69],
        [81, 70, 82, 66, 56],
        [37, 69, 60, 64, 49],
        [18, 22, 39, 49, 48],
        [18,  6, 35, 46, 45],
        [ 3,  2,  3, 39, 44]]])

2️⃣ En caso de que sea bidimensional

In [19]:
# Crea un array

bidimensional = np.random.randint(1, 100, (6,5))
bidimensional

array([[64, 45, 25, 85, 28],
       [23, 73, 13, 65, 90],
       [11,  4, 66, 77, 67],
       [46,  3, 17,  2, 94],
       [30,  7, 73, 55, 81],
       [46,  7, 18, 73, 33]])

In [20]:
# La media de los elementos

np.mean(bidimensional) 

44.03333333333333

In [21]:
# La media de las columnas y redondéalo a dos decimales

np.round(np.mean(bidimensional, axis = 1) , 2)

array([49.4, 52.8, 45. , 32.4, 49.2, 35.4])

In [23]:
# El valor máximo de cada fila

np.max(bidimensional, axis = 1)


array([85, 90, 77, 94, 81, 73])

In [24]:
# El valor mínimo de cada fila

np.min(bidimensional, axis = 1)


array([25, 13,  4,  2,  7,  7])

In [25]:
# Hay algun valor que sea mayor que 90 en tu *array* 
np.any(bidimensional)

True

In [26]:
# Donde los podemos encontrar, cuáles son sus índices

np.where(bidimensional > 90)

(array([3]), array([4]))

In [27]:
# Ordena el *array* de mayor a menor

-np.sort(-bidimensional)

array([[85, 64, 45, 28, 25],
       [90, 73, 65, 23, 13],
       [77, 67, 66, 11,  4],
       [94, 46, 17,  3,  2],
       [81, 73, 55, 30,  7],
       [73, 46, 33, 18,  7]])