In [1]:
import numpy as np

**EJERCICIO 1** Crea dos *arrays* de una dimensión con 6 elementos aleatorios del 1-10. Una vez que los tengamos:

- ¿Qué elementos son comunes en los dos *arrays*?



- ¿Qué elementos están en el primer *array* pero no en el segundo? ¿Qué pasa si cambio el orden de entrada de los arrays? 


- ¿Qué elementos únicos vamos a encontrar en los *arrays* ?

In [27]:
# crea dos arrays unidimensionales

array1 = np.random.randint(1, 10, 6)
array2 = np.random.randint(1, 10, 6)

In [28]:
array1

array([2, 9, 5, 3, 3, 5])

In [29]:
array2

array([3, 7, 6, 7, 7, 8])

In [30]:
# ¿Qué elementos son comunes en los dos *arrays*?

np.intersect1d(array1, array2)

array([3])

In [31]:
# ¿Qué elementos están en el primer *array* pero no en el segundo? 

np.setdiff1d(array1, array2)

array([2, 5, 9])

En este caso estamos viendo los elementos que están en el *array1* pero no en el dos

In [32]:
# si le damos la vuelta

np.setdiff1d(array2, array1)

array([6, 7, 8])

Nos está indicando que solo el número 4 está en el *array2* pero no en el *array1* 

In [33]:
# ¿Qué elementos únicos vamos a encontrar en cada uno de los *arrays* ?


np.setxor1d(array1, array2)

array([2, 5, 6, 7, 8, 9])

- los números 2,5,y 9 son únicos del *array1*

- los números 6,7,8 son únicos del *array2* 

**EJERCICIO 2** Trabajemos con números aleatorios: 

- Crea datos aleatorios para las tres distribuciones explicadas en este jupyter. Todas deben tener ser bidimensionales.


- Guarda cada una de las distribuciones en un archivo `.txt`

In [52]:
uniforme = np.random.uniform(1,200, size = (2,3))
uniforme

array([[ 64.84246294,  19.64571982, 116.96763485],
       [106.30297996, 128.0790612 ,  29.61193152]])

In [54]:
np.savetxt('uniforme.txt', uniforme)

In [53]:
binomial = np.random.binomial(4, 0.8,  size = (2,3))
binomial

array([[4, 3, 3],
       [2, 3, 4]])

In [55]:
np.savetxt('binomial.txt', binomial)

In [56]:
normal = np.random.normal(loc = 4, scale = 0.6,  size = (2,3))
normal

array([[5.28549586, 4.53336962, 4.09128847],
       [4.18100928, 3.68497877, 3.51134272]])

In [57]:
np.savetxt('tridimensional.txt', normal)