**EJERCICIO 1** Genera un array bidimensional de 4 x 3 con valores aleatorios.

Reto: hemos visto que hay al menos tres formas de hacerlo con `np.random` hay.

Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 

In [12]:
# solución 1

array1 = np.random.randint(23, 100, (4,3), dtype= int)
array1

array([[67, 90, 67],
       [96, 26, 37],
       [62, 88, 64],
       [34, 24, 88]])

In [13]:
array1.ndim

2

In [14]:
array1.dtype

dtype('int64')

In [15]:
# solución 2

array2 = np.random.rand(4,3)
array2

array([[0.03702326, 0.40748701, 0.74528526],
       [0.94001842, 0.78061514, 0.75246887],
       [0.04092871, 0.17691377, 0.08919138],
       [0.83731217, 0.28586655, 0.72650846]])

In [16]:
array2.ndim

2

In [17]:
array2.dtype

dtype('float64')

In [18]:
# solución 3

array3 = np.random.random_sample((4,3))
array3

array([[0.07908967, 0.34041617, 0.44508208],
       [0.07929671, 0.27642167, 0.16099021],
       [0.4962988 , 0.78486964, 0.55612226],
       [0.9220936 , 0.7336826 , 0.23263741]])

In [19]:
array3.ndim

2

In [21]:
array3.dtype

dtype('float64')

**EJERCICIO 2** Crea tres arrays (unidimensional, bidimensional y multidimensional) usando el método np.array(). 

Las listas para crear los *arrays* son las siguientes

```python
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]
lista3 = [[[1,2,3],[1,2,3],[1,2,3]]]
```

**Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido

In [38]:
# unidimensional
lista1 = [34,56,71,98, 10]

unidimensional = np.array(lista1)
print("la matriz es:")
print(unidimensional,"\n")

# bonus
print("las caractéristicas de esta matriz son:","\n")
print("dimensiones --> ", unidimensional.ndim)
print("forma --> ",unidimensional.shape)
print("tamaño --> ",unidimensional.size)
print("tipo de dato --> ",unidimensional.dtype)

la matriz es:
[34 56 71 98 10] 

las caractéristicas de esta matriz son: 

dimensiones -->  1
forma -->  (5,)
tamaño -->  5
tipo de dato -->  int64


In [30]:
# bidimensional
lista2 = [[23,45,89, 56], [12,43,82,44]]

bidimensional = np.array(lista2)
print("la matriz es:")
print(bidimensional,"\n")

# bonus
print("las caractéristicas de esta matriz son:","\n")
print("dimensiones --> ", bidimensional.ndim)
print("forma --> ",bidimensional.shape)
print("tamaño --> ",bidimensional.size)
print("tipo de dato --> ",bidimensional.dtype)

dimensiones -->  2
forma -->  (2, 4)
tamaño -->  8
tipo de dato -->  int64


In [40]:
# multidimensional
lista3 = [[[1,2,3],[1,2,3],[1,2,3]], [[1,2,3],[1,2,3],[1,2,3]]]

tridimensional = np.array(lista3)
print("la matriz es:")
print(tridimensional,"\n")


# bonus
print("las caractéristicas de esta matriz son:","\n")
print("dimensiones --> ", tridimensional.ndim)
print("forma --> ",tridimensional.shape)
print("tamaño --> ",tridimensional.size)
print("tipo de dato --> ",tridimensional.dtype)

la matriz es:
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]] 

las caractéristicas de esta matriz son: 

dimensiones -->  3
forma -->  (2, 3, 3)
tamaño -->  18
tipo de dato -->  int64


**EJERICICIO 3** Crea una matriz solo de unos utilizando como referencia la matriz tridimensional creada en el ejercicio anterior.

In [41]:
tridimensional

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [43]:
unos = np.ones_like(tridimensional)
unos

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

**EJERICICIO 4** Crea un ejercicio con un *array** de todo 0 con cuatro dimensiones. 

Explica el array:
- ¿Cuántas dimensiones hay? 
- ¿Qué tamaño tiene?
- ¿Qué forma tiene?

In [49]:
cuatro = np.zeros((3,2,3,6))
cuatro

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])

**EJERCICIO 5** Crea un *array* vacío de 2 x 5 X 4. 

- ¿Qué valores nos han salido en el *array*?  

- ¿Por qué nos salen esos valores?

In [50]:
vacio = np.empty((2,5,4))
vacio

array([[[ 2.31584178e+077, -2.68678977e+154,  1.94917935e-153,
          1.50627316e-065],
        [ 3.11187312e+161,  1.15873714e-028,  1.96097649e+243,
          3.60383586e-143],
        [ 1.24889323e+137,  1.61526682e+136,  9.31466234e+242,
          1.15873714e-028],
        [ 1.96567925e-062,  1.12916072e+261,  6.20428116e+223,
          1.01811692e+131],
        [ 3.31259071e-033,  1.39736850e-076,  7.00205015e-077,
          0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  6.94109034e-310,
          6.94108982e-310],
        [ 6.94108983e-310,  2.23943187e-314,  6.94109034e-310,
          6.94108855e-310],
        [ 6.94108981e-310,  6.94109034e-310,  6.94108982e-310,
          2.65534875e-312],
        [ 0.00000000e+000,  4.72828195e-308,  6.94108813e-310,
          2.85075317e-308]]])

En este caso nos salen valores de cero o muy cercanos a cero. Esto es así porque cuando creamos un *array* vacío los valores se rellenaran en función del último *array* guardado en memoria. Como nuestro *array* anterior es de ceros, los valores en este caso salen cercanos a 0

**EJERCICIO 6** ¿Qué diferencia hay entre un *array* creado con `np.eye` y `np.identity`?

Mientras que un *array* creado con `np.identity` nos va a crear una matriz identidad, un *array* creado con `np.eye` por defecto nos crea una matriz identidad, sin embargo, podemos cambiar donde queremos la diagonal de unos. 

**EJERCICIO 7** En este ejercicio vamos a crear dos arrays:

- Un array tridimensional 5x2x3 con todos los valores iguales a 1.


- Un array tridimensional de 2 x 3 x 5 con números aleatorios entre 0-1

Intenta sumarlos entre ellos. ¿Puedes? ¿Por qué?

In [2]:
aar3 = np.random.random_sample((2,3,5))
unos = np.ones((5,2,3))

In [3]:
np.add(aar3, unos)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

En este caso no se puedes sumar porque las formas de los dos *arrays* no son las mismas

**EJERCICIO 8** Crea dos *arrays* de tres dimensiones. En este caso, puedes asignarles los valores que quieras. Después de crearlos:

- Sumalos


- Restalos


- Divídelos


- Multiplicalos

In [12]:
array8_1 = np.random.rand(3,2,5)
array8_2 = np.random.random_sample((3,2,5))

In [13]:
array8_1

array([[[0.69554299, 0.96148601, 0.5665355 , 0.52944095, 0.13068945],
        [0.14253603, 0.64708847, 0.7698376 , 0.65038209, 0.56502048]],

       [[0.83715595, 0.70102966, 0.14309477, 0.4591731 , 0.78870664],
        [0.6351653 , 0.79152715, 0.11427132, 0.80416867, 0.04264439]],

       [[0.18410602, 0.0952002 , 0.65802243, 0.3281392 , 0.12493219],
        [0.91927016, 0.71567274, 0.94202728, 0.68980266, 0.0147981 ]]])

In [14]:
array8_2

array([[[0.42230117, 0.98795698, 0.16436692, 0.4502371 , 0.55651371],
        [0.49045159, 0.85533866, 0.51594823, 0.5985374 , 0.3702334 ]],

       [[0.59880209, 0.1048884 , 0.72072456, 0.8037768 , 0.42206807],
        [0.61027182, 0.50171142, 0.25155695, 0.70845188, 0.63452989]],

       [[0.56310764, 0.47084599, 0.56588356, 0.56513161, 0.94905369],
        [0.12923022, 0.59932268, 0.74252179, 0.37180389, 0.13405274]]])

In [15]:
# suma

np.add(array8_1, array8_2)

array([[[1.11784416, 1.94944299, 0.73090242, 0.97967805, 0.68720316],
        [0.63298762, 1.50242713, 1.28578583, 1.24891949, 0.93525388]],

       [[1.43595804, 0.80591806, 0.86381933, 1.26294989, 1.21077471],
        [1.24543712, 1.29323857, 0.36582826, 1.51262055, 0.67717427]],

       [[0.74721366, 0.56604619, 1.223906  , 0.89327081, 1.07398587],
        [1.04850037, 1.31499543, 1.68454907, 1.06160655, 0.14885085]]])

In [16]:
# resta 

np.subtract(array8_1, array8_2)

array([[[ 0.27324182, -0.02647097,  0.40216858,  0.07920385,
         -0.42582425],
        [-0.34791555, -0.20825019,  0.25388937,  0.05184469,
          0.19478708]],

       [[ 0.23835386,  0.59614125, -0.57762979, -0.3446037 ,
          0.36663858],
        [ 0.02489349,  0.28981573, -0.13728563,  0.09571678,
         -0.5918855 ]],

       [[-0.37900161, -0.37564579,  0.09213887, -0.23699241,
         -0.8241215 ],
        [ 0.79003994,  0.11635006,  0.19950549,  0.31799876,
         -0.11925464]]])

In [17]:
# multiplicación

np.multiply(array8_1, array8_2)

array([[[0.29372862, 0.94990682, 0.0931197 , 0.23837396, 0.07273047],
        [0.06990702, 0.55347978, 0.39719635, 0.38927801, 0.20918945]],

       [[0.50129073, 0.07352988, 0.10313192, 0.36907268, 0.33288789],
        [0.38762348, 0.39711821, 0.02874574, 0.56971481, 0.02705914]],

       [[0.10367151, 0.04482463, 0.37236408, 0.18544183, 0.11856735],
        [0.11879748, 0.42891891, 0.69947578, 0.25647131, 0.00198373]]])

In [18]:
# división 

np.divide(array8_1, array8_2)

array([[[1.64703069, 0.97320636, 3.44677321, 1.17591586, 0.234836  ],
        [0.29062202, 0.75652896, 1.49208303, 1.08661896, 1.52611969]],

       [[1.39805116, 6.68357634, 0.19854294, 0.57126941, 1.86867169],
        [1.04079082, 1.57765424, 0.45425627, 1.13510696, 0.06720627]],

       [[0.32694642, 0.20218968, 1.16282302, 0.58064209, 0.13163869],
        [7.11343036, 1.19413592, 1.26868637, 1.85528627, 0.11039017]]])